import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className="bg-no-repeat bg-center bg-pr-100"
                style={{
                    backgroundImage: `url('/scg-lines-bg.svg')`,
                    backgroundPosition: 'center -650px'
                }}
            >
                {children}
            </body>
        </html>
    );
}
